# config.yml

development: true
ssh-key: /home/nate/ssh-key

dns:
  rname: info.example.com
  nameservers:
    - ns1.example.dev
    - ns2.example.dev
  prefix4: 203.0.113.0/24
  prefix6: 2001:db8:2::/48
  bind_addresses4:
    - 203.0.113.2
    - 203.0.113.3
  bind_addresses6:
    - 2001:db8:2::2
    - 2001:db8:2::3
  network_config: |
    #!/bin/bash
    ip link del local
    ip link add local type dummy
    ip addr add 203.0.113.2/24 dev local
    ip addr add 203.0.113.3/24 dev local
    ip addr add 2001:db8:2::2/48 dev local
    ip addr add 2001:db8:2::3/48 dev local
    ip addr add 2001:db8:2::4/48 dev local
    ip link set dev local up

email:
  username: noreply@example.com
  password: email-password
  server: mail.example.com

proxy:
  server4: 192.0.2.100
  server6: 2001:db8::100

  prefix4: 192.0.2.0/23
  prefix6: 2001:db8::/47

  network_config: |
    #!/bin/bash
    ip link del local
    ip link add local type dummy
    ip addr add 192.0.2.100/23 dev local
    ip addr add 2001:db8::100/47 dev local
    ip link set dev local up

  # Hosts allowed to access caches (controller and monitoring IPs)
  allowed_hosts:
    - 192.0.2.2
    - 192.0.2.5

monitoring_host: user@monitoring.example.com

collector:
  host: 192.0.2.100
  asn: 65530
