name: Deploy backend
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "backend"
          target: "/home/nate/"

      - name: Reload Caddy config
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: sudo caddy reload -config /etc/caddy/Caddyfile

      - name: Restart backend services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: sudo systemctl daemon-reload ; sudo systemctl restart packetframe-orchestrator ; sudo systemctl restart packetframe-api ; sudo caddy reload -config /etc/caddy/Caddyfile
