name: Build and deploy frontend
on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build frontend
        run: cd frontend/ ; yarn install ; yarn build

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "frontend/public/"
          target: "/home/nate/"
          strip_components: 1
